### ISSUE TITLE
Task 033. Create work plan report

### ISSUE THREAD

**Issue by nicolasdeory** [nicolasdeory/DP2-Project#41]
Item 1: reports

- [x] Produce a report in which you describe your work plan.  It must report on the tasks performed to produce this deliverable.  For each task, you must provide a title, a short description, worker name(s), start and end-dates, and total number of hours.

- [x] Produce a budget. It must take the amortisation of your computers and the personnel costs into account.  To compute the amortisation, assume that it is linearly distributed along three years.  To compute the personnel costs, assume that a manager’s work hour or an analyst’s work hour costs approximately 25€ and a worker’s work hour costs approximately 15€. 

- [x] Produce a progress report in which you describe how the work in your workgroup has gone on.  Please, do not write on your subjective impressions; make a point of writing a concise and objective progress report.
